### ISSUE TITLE
It's unclear how to jump to placeholders

### ISSUE THREAD

**Issue by fwSmit** [LucHermitte/lh-brackets#20] opened 2018-09-11 17:54 UTC
The placeholders that get inserted by lh-brackets after typing brackets characters seem to not work in the way they're supposed to. 
I can't find any shortcuts to jump to a placeholder, nor do they get deleted when I go from insert mode to normal mode. So for me the placeholder characters don't seem to do anything and only get in the way.
There isn't a lot of documentation that can help me with this. 
So my question is: How are you supposed to work with these placeholder characters?

**Comment by LucHermitte** [comment] 2018-09-11 20:28
Damn. I though I provide mappings compatible with terminal vim by default, but it's not the case -- supporting META-mappings with terminal is a nightmare, and they are the ones I use everyday...

Also the documentation is quite light on the subject: I've hidden in lh-cpp `:h lh-cpp-first-steps`, step 2 information about the placeholders and the keybindings meant to be defined with vim. Also, in lh-brackets, I provide only the keybindings available with gvim. 

In all cases, you can always get rid of the marker just behind the closing character that this just after the cursor by typing that closing character.

If you have several consecutive things that can be closed, you an type `<m-end>` with gvim to close everything. In C and C++ case, hitting `;` can also close many things.

Stuff I usually **type** is 
- `find(v` +`CTRL-Xbe`+ `,[](auto e){` + `META-r` (gvim is required here) + `f(e` + `META-DEL` + `META-DEL`
- or `f(g(y;`

You know what? I still recommend to provide `<C-J>` by default to jump to next marker. But I have ideas for the other mappings (jump-backward, insert-marker, close-and-jump-to-last, and jump-outside), let me know.

**Comment by fwSmit** [comment] 2018-09-13 15:47
Yep the mapping <c-j> and <C-Xbe> work very well.  
I have a few things to note however
- Sometimes when using templates like if\<space> the cursor will move to the wrong place (in this case i\<cursor>f () {
- You're saying that most of the bugs are because I use terminal vim and you use gvim, but it seems like they behave the same in all cases I tested. 
- What are the <m-..> and <s-..> bindings? 
- When creating a function you don't want the placeholders and it's annoying to remove them. Perhaps going to normal mode or saving a file should remove all placeholders. When you don't remove them, the file won't compile.

**Comment by LucHermitte** [comment] 2018-09-13 17:00
> Sometimes when using templates like if<space> the cursor will move to the wrong place (in this case i<cursor>f () {

You mean the abbreviation? (not the template from mu-template). That's odd. Can you determine the sequence of operations that lead to that bug? Also, Have you changed your marker characters? What's your file encoding? And what's the encoding of your Vim instance?

> You're saying that most of the bugs are because I use terminal vim and you use gvim, but it seems like they behave the same in all cases I tested.

What I meant is that I seldom use terminal vim, and that my terminal mappings for lh-brackets were in another file. That's why I missed the fact that I did not provide terminal-friendly mappings

> What are the <m-..> and <s-..> bindings?

`M` stands for _meta_ (alt key nowadays), and `S` for shift. See `:h <m-` and `:h <s-`

> When creating a function you don't want the placeholders and it's annoying to remove them. Perhaps going to normal mode or saving a file should remove all placeholders. When you don't remove them, the file won't compile.

Good point. I save my files more often than required, removing the placeholders would defeat their purpose.  Regarding compilation, you're right. I could implement this feature as a pre-compile hook that BuildToolsWrapper, but I'm one of the few that could profit from that. What you suggest could be done through an option: "(bpg):maker_auto_remove = always, never, ask-if-found"

> It would be nice to point to the :h lh-cpp-first-steps in the readme of lh-cpp (and perhaps also add some documentation to lh-brackets). I could help with this.

You're right, and you'd be welcomed :)

**Comment by fwSmit** [comment] 2018-09-17 17:36
> You mean the abbreviation? (not the template from mu-template).
yeah
> Can you determine the sequence of operations that lead to that bug?
in the file foo.cpp you have
``` cpp
int main{
    <cursor>
}
```
if you then type if<space> you get
``` cpp
int main(){
    i<cursor>f () {
            «»  
    }   
    «»  
}
```
set encoding? return utf-8

----------------------------------------------------------------------
I think in some general cases you don't want placeholders to be inserted. The cases I can think of are class definitions and function definitions.

**Comment by LucHermitte** [comment] 2018-09-18 16:13
That's definitively odd.
I guess I'll need the extensive list of scripts loaded (`:let @+ = execute(':scriptnames')` + paste into this issue), the current options (`:let @+ = execute(':set')`).

Regarding classes and functions, it's may be quite hard to recognize automatically.
May be I could add a `--placeholder=0` option (or `--placeholder=someoption`) to `:Bracket` and let the end-user either override `{` mappings, or set the `someoption` in the .vimrc or a local vimrc.
Another possibility is to have the mapping on `<cr>` remove the placeholder when hit within a pair of curly brackets.

**Comment by fwSmit** [comment] 2018-10-05 08:39
Sorry for the delay, but here it is:
I have a feeling this bug is related to the indentation, but here are the results of the commands.
I made a custom vimrc which only consists of the lh-cpp plugins. It gives a slightly different (but still wrong) result when using abbreviations 
:let @+ = execute(':scriptnames') gives:
[(https://pastebin.com/YyncAtC5)]
:let @+ = execute(':set') gives:
[https://pastebin.com/jfCDUey1]
It'd be nice if you looked at this.

**Comment by LucHermitte** [comment] 2018-10-09 16:59
Sorry for the delay. I've been quite busy as well lately.

Unfortunately I fail to reproduce the problem.
At best, while editing some LaTeX documents in a VM, sometimes I see the cursor blinking in the wrong position, yet when I start typing, the text goes in the right place.

Let's start some debugging then.

Could tell me what the following displays?

    :iab
    :echo strtrans(lh#cpp#snippets#def_abbr('if ', '\<c-f\>if(!cursorhere!){!mark!}!mark!'))
    "it should be typed from the context where you'd type `if<space>`

And also

    :LHLog file /tmp/vim-if.log
    call lh#map#verbose(1)
    call lh#style#verbose(1)

And then type `if<space>`, and send me the `/tmp/vim-if.log` file generated. Thanks :)

For reference, I obtain: 

```
???:24: grp:ignored: /{\w\+}/, hows: {\w\+}
???:24: grp:empty_braces: /{\_s*}/, hows: {\_s*}
???:24: grp:curly-braces: /\(\%(\<\%(if\|while\|switch\|for\)\>\s*(.\{-})\|\<do\|else\>\|\<\%(namespace\|class\|struct\|union\|enum\).\{-}\S\>\)\s*\|^\)\@<!{/, hows: \(\%(\<\%(if\|while\|switch\|for\)\>\s*(.\{-})\|\<do\|else\>\|\<\%(namespace\|class\|struct\|union\|enum\).\{-}\S\>\)\s*\|^\)\@<!{
???:24: grp:curly-braces: /};\@!/, hows: };\@!
???:24: grp:curly-braces: /{/, hows: {
???:24: grp:curly-braces: /};/, hows: };
???:24: grp:curly-braces: /}/, hows: }
???:24: grp:curly-braces: /\%(\<\%(if\|while\|switch\|for\)\>\s*(.\{-})\|\<do\|else\>\|\<\%(namespace\|class\|struct\|union\|enum\).\{-}\S\>\)\zs{/, hows: \%(\<\%(if\|while\|switch\|for\)\>\s*(.\{-})\|\<do\|else\>\|\<\%(namespace\|class\|struct\|union\|enum\).\{-}\S\>\)\zs{
???:24: grp:spaces.brackets.cf.before: /\<\%(if\|while\|switch\|for\|catch\)\>\zs\s*(/, hows: \<\%(if\|while\|switch\|for\|catch\)\>\zs\s*(
???:24: grp:spaces.brackets.cf.before: /\%(\<\%(if\|while\|switch\|for\|catch\)\>\)\@<!\s*(/, hows: \%(\<\%(if\|while\|switch\|for\|catch\)\>\)\@<!\s*(
???:20: ^Fif (^R=lh#map#_cursor_here()^M) {^@^R=lh#marker#txt()^M^@}^@^R=lh#marker#txt()^M^R=lh#map#_goto_mark()^M
???:4: Using mark ['''R', [1, 0, 0, 0]]
???:10: Record cursor  with mark 'R: |   indent=4
???:8: Returning to mark 1 @ 
???:12: fix indent <- 0 (old_indent:4 - crt_indent:4)
???:30: Restore cursor to 2normal! 9|
```

**Comment by fwSmit** [comment] 2018-10-10 18:43
Even when I try to type the cursor will still be in the wrong place.

:iab [https://pastebin.com/RhakrcTr](https://pastebin.com/RhakrcTr)

:echo strtrans(lh#cpp#snippets#def_abbr('if ', '\<c-f\>if(!cursorhere!){!mark!}!mark!'))
`^Fif (^R=lh#map#_cursor_here()^M) {^@^R=lh#marker#txt()^M^@}^@^R=lh#marker#txt()^M^R=lh#map#_goto_mark()^M`
(no idea what that means) 

[/tmp/vim-if.log](https://pastebin.com/aY4ENu3g)

Somehow after I did the call commands the next few if's, the cursor went to the right place, but the indentation was zero.  
FYI [this](https://pastebin.com/f4pRLhiv) is the vimrc I used for testing

**Comment by LucHermitte** [comment] 2018-10-11 17:52
The strtrans result displays (in a human readable form) how this mapping is actually executed.

I've just updated lh-vim-lib and lh-brackets -- I've fixed the log produced (oddly there was an error that never triggered anything, which is odd). Could you replay the test only with 

```vim
call lh#map#verbose(1)
LHLog file /tmp/vim-if.log
```

please?

Thanks.

**Comment by LucHermitte** [comment] 2018-10-11 22:39
It seems related to `'noexpandtab'` + the default value for `'sw'`. I'm always working with tab expanded into spaces, and `'sw'` set to 4.

Now that I can reproduce the problem, I should be able to find a solution. Can you confirm my analysis? (i.e. that `:set noexpandtab` fixes the problem?)

**Comment by fwSmit** [comment] 2018-10-12 07:52
Noexpandtab is already set by default for me. Before I updated I set expandtab and that indeed solved the problem. 
I see you made the commit on another branch, so I switched to that branch and updated. 
After updating It works with noexpandtab and with expandtab. Great work! You can merge the branch and close this issue now if you want.

**Comment by LucHermitte** [comment] 2018-10-12 11:12
Unfortunately other things are now broken :(

IIRC, I've already struggle in the past with this function because there isn't any simple way to restore cursor on a virtual column which exact value will change after automatic reindentation. I'll first have to add new tests that check the behaviour of the multi-line snippets on:

- insert mode expansion
- visual mode surrounding

with:

- `expandtab` / `noexpandtab`
- `&sw` == 1 * `&tabstop`, 0.5 * `&tabstop`
- multibyte characters before the text inserted

**Comment by fwSmit** [comment] 2018-10-12 11:15
Oh it's more complicated than I thought. I'll stay on the noexpandtab branch and I'll report any bugs I find to you

**Comment by LucHermitte** [comment] 2018-10-12 11:51
So far, I'm aware of the one reported through the integration with travis-CI. :)

**Comment by LucHermitte** [comment] 2018-10-12 16:53
What an headache! It should be better now.

But I still need to provide a lot of tests to be sure everything works correctly.

- [ ] w/ MB characters
- [ ] when line is wrapped in insert mode
- [ ] surround + no expand tab (previously incorrectly indented)
- [ ] insert mode + noexpandtab
- [ ] insert mode + expandtab
- ...

**Comment by fwSmit** [comment] 2018-10-12 16:54
If you help me a bit I can maybe write those tests. Can't be too hard right?

**Comment by LucHermitte** [comment] 2018-10-15 13:08
Well. I'd glad of any help. But I have to be honest, this is quite cumbersome to write and to test locally.

These tests should be written in `spec/cpp_spec.rb` -- it should have been `spec/c_spec.rb`, but I'll fix that another time. If you check my commits in that branch, you'll see a few changes in that file. The cumbersome part, regarding test writing, is that the file will need to have some mixed-indentation to test all the possible situations. You shouldn't have to much trouble to understand what happens here. You'll start from a stable situation, you should not encounter one of these impossible to investigate test failures I keep experimenting with the stack I've chosen.

Right now, the tests are surrounding tests that use the visual mapping from `spec/support/c-snippet.vim`. I should also copy the abbreviation from lh-cpp on `if` to that file to test the case you've observed.

The cumbersome part regarding testing is that one need to install ruby + rake + bundle + vim_runner + vim-flavor + vim-UT locally. But that's not enough, I usually trick vim-flavor with symlink in `~/.vim-flavor/repos/`:

```
LucHermitte_lh-vim-lib -> ~/.vim/addons/lh-vim-lib/
LucHermitte_vim-UT -> ~/.vim/addons/UT/
LucHermitte_lh-style ->  ~/.vim/addons/lh-style/
...
```

A part of the process is described in https://github.com/LucHermitte/vim-UT/blob/master/doc/rspec-integration.md


So. If you feel like it, I'll welcome any help, but don't feel obliged to contribute on that part.

**Comment by LucHermitte** [comment] 2018-10-17 17:12
A few tests to go (`&sw == 2 * &tabstop`), and most usual cases should have been covered. :)

**Closed** 2018-10-17 17:43 UTC
Labels: Doc, bug
