### ISSUE TITLE
Redo insert with '.' broken

### ISSUE THREAD

**Issue by galou** [LucHermitte/lh-brackets#2] opened 2015-09-21 12:19 UTC
Repeat last insertion (with '.' in normal mode) is broken when lh-brackets intervenes.

**Comment by LucHermitte** [comment] 2015-09-21 12:50
I know. :(

Actually this is broken with all bracketing plugins since a few (minor) versions of vim -- NB lh-brackets did not support redo at that time.

A patch has been proposed to vim to help us define such mappings that can be redone.
Last I checked (3-4 weeks ago), the patch hasn't been merged. I'll have to check again.

I leave the issue open in the mean time.

**Comment by LucHermitte** [comment] 2015-11-04 17:48
redo shall now be handled since commit 3ef497fa204f581ceb24add5fb0a5e40710a6315 (branch repo-repeat)

Intensive testing will be conducted before a final merge of the branch.

**Comment by galou** [comment] 2015-11-06 08:44
Great! Thanks! I'll test it.

**Comment by LucHermitte** [comment] 2015-11-20 15:32
It should work correctly now.
I may refactor the internal functions as `<localleader>1` from lh-cpp doesn't work anymore. But at least this time, I will have non-regression tests.
I close the issue.

**Closed by LucHermitte** 2015-11-20 15:32 UTC
